server:
  port: 8887

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    #url: jdbc:sqlite:/Users/durantjiang/software/sqlite/info.db
    url: jdbc:sqlite:/root/sqlite/info.db
    username:
    password:


# mapper文件映射路径和实体映射路径
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhengjiang.manage.model

## 打印sql语句
logging:
  level:
     com.zhejiang.manage.mapper : debug



